// Iconos del portal de clientes.
//
// Antes todo el portal usaba la fuente "Material Symbols Rounded" servida por
// Google Fonts con `display=block`: hasta que esa hoja de estilo + la fuente
// (varios cientos de KB desde un tercer dominio) terminaban de cargar, el
// sidebar y el bottom nav se veían vacíos y descuadrados. Como son SVG del
// bundle, estos iconos pintan en el primer render, sin red de por medio.
//
// La clave sigue siendo el nombre de Material Symbols porque hay valores
// guardados en la base de datos (logros_config.icon, mascota_eventos.icon,
// notificaciones.icon) y en configs del propio código. Si aparece un nombre
// que no está mapeado, se cae al icono de estrella en vez de romper la vista;
// al agregar un icono nuevo en el admin, agrégalo también acá.
import {
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  Bandage,
  Bell,
  Bookmark,
  BookOpen,
  BookOpenText,
  Bug,
  Cake,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Camera,
  Check,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CirclePlay,
  CirclePlus,
  CircleUser,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Clock,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  FileText,
  Fingerprint,
  Folder,
  Gem,
  Gift,
  GraduationCap,
  Handshake,
  HeartPulse,
  History,
  House,
  Lock,
  LockOpen,
  LogOut,
  MapPin,
  Medal,
  Package,
  Palette,
  PawPrint,
  Pencil,
  Phone,
  Pill,
  Play,
  Plus,
  QrCode,
  Route,
  ScrollText,
  Settings,
  Shapes,
  Share2,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Star,
  Stethoscope,
  Syringe,
  Ticket,
  Timer,
  Trash2,
  TriangleAlert,
  Truck,
  User,
  UserCog,
  UserPlus,
  Users,
  Utensils,
  Weight,
  X,
  type LucideIcon,
} from "lucide-react";

const ICONOS: Record<string, LucideIcon> = {
  add_circle: CirclePlus,
  add: Plus,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  article: FileText,
  assignment: ClipboardList,
  auto_stories: BookOpenText,
  badge: BadgeCheck,
  bookmark: Bookmark,
  bug_report: Bug,
  cake: Cake,
  calendar_month: CalendarDays,
  call: Phone,
  category: Shapes,
  check_circle: CircleCheck,
  check: Check,
  chevron_right: ChevronRight,
  close: X,
  confirmation_number: Ticket,
  content_copy: Copy,
  credit_card: CreditCard,
  delete: Trash2,
  description: FileText,
  diamond: Gem,
  diversity_2: Users,
  diversity_3: Users,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  event_available: CalendarCheck,
  event_repeat: CalendarClock,
  event: Calendar,
  fact_check: ClipboardCheck,
  fingerprint: Fingerprint,
  folder: Folder,
  group_add: UserPlus,
  handshake: Handshake,
  healing: Bandage,
  history_edu: ScrollText,
  history: History,
  home: House,
  inventory_2: Package,
  keyboard_arrow_right: ChevronRight,
  local_shipping: Truck,
  location_on: MapPin,
  lock_open: LockOpen,
  lock: Lock,
  logout: LogOut,
  manage_accounts: UserCog,
  medical_information: ClipboardPlus,
  medical_services: Stethoscope,
  menu_book: BookOpen,
  military_tech: Medal,
  monitor_heart: HeartPulse,
  monitor_weight: Weight,
  more_horiz: Ellipsis,
  notifications: Bell,
  palette: Palette,
  person_add: UserPlus,
  person: User,
  pest_control: Bug,
  pets: PawPrint,
  photo_camera: Camera,
  picture_as_pdf: FileText,
  pill: Pill,
  play_arrow: Play,
  play_circle: CirclePlay,
  qr_code_2: QrCode,
  redeem: Gift,
  restaurant: Utensils,
  route: Route,
  schedule: Clock,
  school: GraduationCap,
  settings: Settings,
  share: Share2,
  shopping_bag: ShoppingBag,
  shopping_basket: ShoppingBasket,
  shopping_cart_checkout: ShoppingCart,
  star: Star,
  stethoscope: Stethoscope,
  timer: Timer,
  vaccines: Syringe,
  verified_user: ShieldCheck,
  warning: TriangleAlert,
  wc: CircleUser,
  workspace_premium: Award,
};

/** Nombres válidos, para poblar el selector de íconos del admin. */
export const ICONOS_PORTAL = Object.keys(ICONOS).sort();

interface PortalIconProps {
  name: string;
  className?: string;
}

// El tamaño se toma del `font-size` heredado (h-[1em] w-[1em]) para que las
// mismas clases que usaba la fuente de iconos (text-[18px], text-4xl, …)
// sigan funcionando sin tocar cada llamada.
export function PortalIcon({ name, className = "" }: PortalIconProps) {
  const Icon = ICONOS[name] ?? Star;
  return <Icon aria-hidden="true" className={`inline-block h-[1em] w-[1em] shrink-0 align-middle ${className}`} />;
}
