// Traducciones al español de las razas que devuelven las APIs públicas
// dog.ceo (perros) y TheCatAPI (gatos). Ambas APIs solo responden en inglés,
// así que useRazasSugeridas.ts usa estos diccionarios para traducir el
// autocompletado de raza. Si un nombre no está mapeado, se muestra tal cual
// vino de la API (mejor un nombre en inglés que una raza faltante).

export const TRADUCCION_RAZA_PERRO: Record<string, string> = {
  Affenpinscher: "Affenpinscher",
  "Afghan Hound": "Lebrel Afgano",
  Airedale: "Terrier Airedale",
  Akita: "Akita",
  "American Terrier": "Terrier Americano",
  "Andalusian Terrier": "Terrier Andaluz",
  Appenzeller: "Boyero de Appenzell",
  "Australian Cattledog": "Boyero Australiano",
  "Australian Terrier": "Terrier Australiano",
  Basenji: "Basenji",
  "Basset Hound": "Basset Hound",
  Beagle: "Beagle",
  "Bedlington Terrier": "Terrier Bedlington",
  "Bernese Mountain": "Boyero de Berna",
  "Bichon Frise": "Bichón Frisé",
  "Blenheim Spaniel": "Spaniel Blenheim",
  "Blood Hound": "Sabueso de Sangre",
  Bluetick: "Bluetick Coonhound",
  "Border Collie": "Border Collie",
  "Border Terrier": "Terrier Border",
  Borzoi: "Borzoi",
  "Boston Bulldog": "Bulldog de Boston",
  "Boston Terrier": "Terrier de Boston",
  Bouvier: "Bouvier de Flandes",
  Boxer: "Bóxer",
  Brabancon: "Grifón de Bruselas",
  Briard: "Briard",
  "Brittany Spaniel": "Spaniel Bretón",
  "Bull Mastiff": "Bullmastiff",
  "Cairn Terrier": "Terrier Cairn",
  "Cardigan Corgi": "Corgi Cardigan",
  "Caucasian Ovcharka": "Ovcharka del Cáucaso",
  Cavapoo: "Cavapoo",
  "Chesapeake Retriever": "Retriever de Chesapeake",
  Chihuahua: "Chihuahua",
  Chow: "Chow Chow",
  Clumber: "Clumber Spaniel",
  Cockapoo: "Cockapoo",
  "Cocker Spaniel": "Cocker Spaniel",
  "Collie Rough": "Collie de Pelo Largo",
  Coonhound: "Coonhound",
  Cotondetulear: "Coton de Tulear",
  "Curly Retriever": "Retriever de Pelo Rizado",
  Dachshund: "Teckel (Salchicha)",
  Dalmatian: "Dálmata",
  "Dandie Terrier": "Terrier Dandie Dinmont",
  Dhole: "Cuón",
  Dingo: "Dingo",
  Doberman: "Dóberman",
  "English Bulldog": "Bulldog Inglés",
  "English Hound": "Sabueso Inglés",
  "English Mastiff": "Mastín Inglés",
  "English Setter": "Setter Inglés",
  "English Sheepdog": "Pastor Inglés Antiguo",
  "English Springer": "Springer Spaniel Inglés",
  Entlebucher: "Boyero de Entlebuch",
  Eskimo: "Perro Esquimal Americano",
  "Flatcoated Retriever": "Retriever de Pelo Liso",
  "Fox Terrier": "Fox Terrier",
  "French Bulldog": "Bulldog Francés",
  "German Pointer": "Braco Alemán",
  "Germanlonghair Pointer": "Braco Alemán de Pelo Largo",
  "Giant Schnauzer": "Schnauzer Gigante",
  "Golden Retriever": "Golden Retriever",
  "Gordon Setter": "Setter Gordon",
  "Great Dane": "Gran Danés",
  Groenendael: "Pastor Belga Groenendael",
  Havanese: "Bichón Habanero",
  Husky: "Husky Siberiano",
  "Ibizan Hound": "Podenco Ibicenco",
  "Indian Bakharwal": "Bakharwal Indio",
  "Indian Chippiparai": "Chippiparai Indio",
  "Indian Gaddi": "Perro Pastor Gaddi",
  "Indian Greyhound": "Galgo Indio",
  "Indian Mastiff": "Mastín Indio",
  "Indian Mudhol": "Galgo Mudhol",
  "Indian Pariah": "Perro Paria Indio",
  "Indian Rajapalayam": "Rajapalayam Indio",
  "Indian Sheepdog": "Pastor Indio",
  "Indian Spitz": "Spitz Indio",
  "Irish Setter": "Setter Irlandés",
  "Irish Spaniel": "Spaniel Irlandés",
  "Irish Terrier": "Terrier Irlandés",
  "Irish Wolfhound": "Lobero Irlandés",
  "Italian Greyhound": "Galgo Italiano",
  "Italian Segugio": "Segugio Italiano",
  "Japanese Spaniel": "Chin Japonés",
  "Japanese Spitz": "Spitz Japonés",
  Keeshond: "Keeshond",
  Kelpie: "Kelpie",
  "Kelpie Australian": "Kelpie Australiano",
  "Kerryblue Terrier": "Terrier Kerry Blue",
  Kombai: "Kombai",
  Komondor: "Komondor",
  Kuvasz: "Kuvasz",
  Labradoodle: "Labradoodle",
  Labrador: "Labrador Retriever",
  "Lakeland Terrier": "Terrier Lakeland",
  "Lapphund Finnish": "Lapphund Finlandés",
  Leonberg: "Leonberger",
  Lhasa: "Lhasa Apso",
  Malamute: "Malamute de Alaska",
  Malinois: "Pastor Belga Malinois",
  Maltese: "Maltés",
  "Medium Poodle": "Caniche Mediano",
  Mexicanhairless: "Xoloitzcuintle",
  "Miniature Pinscher": "Pinscher Miniatura",
  "Miniature Poodle": "Caniche Miniatura",
  "Miniature Schnauzer": "Schnauzer Miniatura",
  Mix: "Mestizo",
  Newfoundland: "Terranova",
  "Norfolk Terrier": "Terrier Norfolk",
  "Norwegian Buhund": "Buhund Noruego",
  "Norwegian Elkhound": "Elkhound Noruego",
  "Norwich Terrier": "Terrier Norwich",
  Otterhound: "Otterhound",
  Papillon: "Papillón",
  "Patterdale Terrier": "Terrier Patterdale",
  Pekinese: "Pekinés",
  Pembroke: "Corgi Galés de Pembroke",
  Pitbull: "Pitbull",
  "Plott Hound": "Sabueso Plott",
  Pomeranian: "Pomerania",
  Pug: "Pug (Carlino)",
  Puggle: "Puggle",
  Pyrenees: "Gran Pirineo",
  Redbone: "Redbone Coonhound",
  "Rhodesian Ridgeback": "Ridgeback de Rodesia",
  Rottweiler: "Rottweiler",
  "Russell Terrier": "Jack Russell Terrier",
  Saluki: "Saluki",
  Samoyed: "Samoyedo",
  Schipperke: "Schipperke",
  "Scottish Deerhound": "Lebrel Escocés",
  "Scottish Terrier": "Terrier Escocés",
  "Sealyham Terrier": "Terrier Sealyham",
  Sharpei: "Shar Pei",
  "Shepherd Australian": "Pastor Australiano",
  "Shepherd German": "Pastor Alemán",
  "Shetland Sheepdog": "Pastor de Shetland",
  Shiba: "Shiba Inu",
  Shihtzu: "Shih Tzu",
  "Silky Terrier": "Terrier Sedoso Australiano",
  "Spanish Waterdog": "Perro de Agua Español",
  "Staffordshire Bullterrier": "Bull Terrier Staffordshire",
  "Standard Poodle": "Caniche Estándar",
  Stbernard: "San Bernardo",
  "Sussex Spaniel": "Spaniel Sussex",
  "Swedish-farmdog Danish": "Perro de Granja Sueco",
  "Swiss Mountain": "Boyero de las Montañas Suizas",
  Tervuren: "Pastor Belga Tervuren",
  "Tibetan Mastiff": "Mastín Tibetano",
  "Tibetan Terrier": "Terrier Tibetano",
  "Toy Poodle": "Caniche Toy",
  "Toy Terrier": "Terrier Toy Inglés",
  Vizsla: "Vizsla",
  "Walker Hound": "Sabueso Walker",
  Weimaraner: "Weimaraner",
  "Welsh Spaniel": "Spaniel Galés",
  "Welsh Terrier": "Terrier Galés",
  "Westhighland Terrier": "West Highland White Terrier",
  "Wheaten Terrier": "Terrier Wheaten",
  Whippet: "Whippet",
  "Wild African": "Perro Salvaje Africano",
  "Yorkshire Terrier": "Yorkshire Terrier",
};

export const TRADUCCION_RAZA_GATO: Record<string, string> = {
  Abyssinian: "Abisinio",
  Aegean: "Egeo",
  "American Bobtail": "Bobtail Americano",
  "American Curl": "Curl Americano",
  "American Shorthair": "Pelo Corto Americano",
  "American Wirehair": "Pelo Alambre Americano",
  "Arabian Mau": "Mau Arábigo",
  "Australian Mist": "Mist Australiano",
  Balinese: "Balinés",
  Bambino: "Bambino",
  Bengal: "Bengalí",
  Birman: "Sagrado de Birmania",
  Bombay: "Bombay",
  "British Longhair": "Pelo Largo Británico",
  "British Shorthair": "Pelo Corto Británico",
  Burmese: "Burmés",
  Burmilla: "Burmilla",
  "California Spangled": "Manchado de California",
  "Chantilly-Tiffany": "Chantilly-Tiffany",
  Chartreux: "Cartujo",
  Chausie: "Chausie",
  Cheetoh: "Cheetoh",
  "Colorpoint Shorthair": "Pelo Corto Colorpoint",
  "Cornish Rex": "Rex Cornish",
  Cymric: "Cymric",
  Cyprus: "Chipriota",
  "Devon Rex": "Rex Devon",
  Donskoy: "Esfinge Rusa (Donskoy)",
  "Dragon Li": "Dragón Li",
  "Egyptian Mau": "Mau Egipcio",
  "European Burmese": "Burmés Europeo",
  "Exotic Shorthair": "Exótico de Pelo Corto",
  "Havana Brown": "Habana Brown",
  Himalayan: "Himalayo",
  "Japanese Bobtail": "Bobtail Japonés",
  Javanese: "Javanés",
  "Khao Manee": "Khao Manee",
  Korat: "Korat",
  Kurilian: "Kurilian Bobtail",
  LaPerm: "LaPerm",
  "Maine Coon": "Maine Coon",
  Malayan: "Malayo",
  Manx: "Manx",
  Munchkin: "Munchkin",
  Nebelung: "Nebelung",
  "Norwegian Forest Cat": "Bosque de Noruega",
  Ocicat: "Ocicat",
  Oriental: "Oriental",
  Persian: "Persa",
  "Pixie-bob": "Pixiebob",
  Ragamuffin: "Ragamuffin",
  Ragdoll: "Ragdoll",
  "Russian Blue": "Azul Ruso",
  Savannah: "Savannah",
  "Scottish Fold": "Scottish Fold (Orejas Dobladas)",
  "Selkirk Rex": "Rex Selkirk",
  Siamese: "Siamés",
  Siberian: "Siberiano",
  Singapura: "Singapura",
  Snowshoe: "Snowshoe",
  Somali: "Somalí",
  Sphynx: "Esfinge (Sphynx)",
  Tonkinese: "Tonkinés",
  Toyger: "Toyger",
  "Turkish Angora": "Angora Turco",
  "Turkish Van": "Van Turco",
  "York Chocolate": "York Chocolate",
};
